# Generated by Django 5.0.6 on 2024-05-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(max_length=10),
        ),
    ]
